---
title: "Lab 5"
author: "Nathan Weitershausen"
format: html
editor: visual
embed-resources: true
---

# Setup

```{r}
library(data.table)
library(dtplyr)
library(dplyr)

# Read met
met <- read.csv("C:/Users/nweit/Downloads/met_all.gz")
met$USAFID <- as.integer(met$USAFID)

met <- met[met$temp > -17, ]

# Download stations data
stations <- read.csv("https://noaa-isd-pds.s3.amazonaws.com/isd-history.csv")
stations$USAF <- as.integer(stations$USAF)

# Dealing with blanks and 999999
stations$USAF[stations$USAF == 999999] <- NA
stations$CTRY[stations$CTRY == ""] <- NA
stations$STATE[stations$STATE == ""] <- NA

# Selecting the three relevant columns, and keeping unique records
stations <- unique(stations[, c('USAF', 'CTRY', 'STATE')])

# Dropping NAs
stations <- stations[!is.na(stations$USAF), ]

# Removing duplicates
stations <- stations[!duplicated(stations$USAF), ]

dat <- merge(
  # Data
  x     = met,      
  y     = stations, 
  # List of variables to match
  by.x  = "USAFID",
  by.y  = "USAF", 
  # Which obs to keep?
  all.x = TRUE,      
  all.y = FALSE
  )

head(dat[, c('USAFID', 'WBAN', 'STATE')], n = 4)
```

# Question 1: Representative station for the US

What is the median station in terms of temperature, wind speed, and atmospheric pressure? Look for the three weather stations that best represent continental US using the quantile() function. Do these three coincide?

```{r}
dat2 <- dat |>
  group_by(USAFID) |>
  summarize(Median_Temp = median(temp, na.rm = TRUE),
            Median_Wind.Speed = median(wind.sp, na.rm = TRUE), Median_Atmospheric.Pressure = median(atm.press, na.rm = TRUE)) |>
  arrange (USAFID) |>
  filter(!is.na(Median_Temp), !is.na(Median_Wind.Speed), !is.na(Median_Atmospheric.Pressure))

Stations_Medians <- dat2 |>
  summarize(
    Median_Temp = quantile(Median_Temp, 0.50, na.rm = TRUE),
    Median_Wind.Speed = quantile(Median_Wind.Speed, 0.50, na.rm = TRUE), Median_Atmospheric.Pressure = quantile(Median_Atmospheric.Pressure, 0.50, na.rm = TRUE))

Stations_Medians

Temperature_Station <-dat2[which.min(abs(dat2$Median_Temp - Stations_Medians["Median_Temp"]))]
Wind.Speed_Station <-dat2[which.min(abs(dat2$Median_Wind.Speed - Stations_Medians["Median_Wind.Speed"]))]
Atmospheric.Pressure_Station <-dat2[which.min(abs(dat2$Median_Atmospheric.Pressure - Stations_Medians["Median_Atmospheric.Pressure"]))]

Stations_Medians <- data.frame(
  Variable = c("Temperature", "Wind speed", "Atmospheric pressure"),
  USAFID = c(Temperature_Station$USAFID, Wind.Speed_Station$USAFID, Atmospheric.Pressure_Station$USAFID),
  Stations_Medians = c(Temperature_Station$Median_Temp, Wind.Speed_Station$Median_Wind.Speed, Atmospheric.Pressure_Station$Median_Atmospheric.Pressure))

Stations_Medians

```
